# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tjob',
            name='appliedOn',
            field=models.DateField(help_text='Please use the following format:  YYYY-MM-DD'),
        ),
    ]
